<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R8DT9RL" failures="1" tests="5" name="adstestcases.AdsLedCreateCampaignTest" time="36.530" errors="0" timestamp="2025-07-29T15:52:43 IST" skipped="0">
  <testcase classname="adstestcases.AdsLedCreateCampaignTest" name="loginTest" time="33.712"/>
  <testcase classname="adstestcases.AdsLedCreateCampaignTest" name="Appselection" time="1.667"/>
  <testcase classname="adstestcases.AdsLedCreateCampaignTest" name="NavigationToLedCampaign" time="0.981"/>
  <testcase classname="adstestcases.AdsLedCreateCampaignTest" name="CreatewithInvalid" time="0.166">
    <failure message="Can&#039;t open workbook - unsupported file type: UNKNOWN" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Can't open workbook - unsupported file type: UNKNOWN
at org.testng.Assert.fail(Assert.java:111)
at adstestcases.AdsLedCreateCampaignTest.CreatewithInvalid(AdsLedCreateCampaignTest.java:504)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- CreatewithInvalid -->
  <testcase classname="adstestcases.AdsLedCreateCampaignTest" name="logSummary" time="0.004"/>
</testsuite> <!-- adstestcases.AdsLedCreateCampaignTest -->
